/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package main.java.erp.backend.api.common;

import io.swagger.annotations.*;
import main.java.erp.backend.model.common.Unit;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-15T00:41:28.115Z")

@Api(value = "units", description = "the units API")
public interface UnitsApi {

    @ApiOperation(value = "Create new unit", notes = "", response = Integer.class, authorizations = {
        @Authorization(value = "APIKeyHeader")
    }, tags={ "ERP - units", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Integer.class),
        @ApiResponse(code = 401, message = "Unauthorized - API key is missing or invalid", response = Error.class),
        @ApiResponse(code = 500, message = "Server error", response = Error.class) })
    
    @RequestMapping(value = "/units",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Integer> createUnit(@ApiParam(value = "Unit to create") @Valid @RequestBody Unit unit);


    @ApiOperation(value = "Delete unit", notes = "", response = Void.class, authorizations = {
        @Authorization(value = "APIKeyHeader")
    }, tags={ "ERP - units", })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Deleted", response = Void.class),
        @ApiResponse(code = 401, message = "Unauthorized - API key is missing or invalid", response = Error.class),
        @ApiResponse(code = 500, message = "Server error", response = Error.class) })

    @RequestMapping(value = "/units/{unitId}",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteUnit(@ApiParam(value = "", required = true) @PathVariable("unitId") Integer unitId);


    @ApiOperation(value = "Returns Unit", notes = "", response = Unit.class, authorizations = {
        @Authorization(value = "APIKeyHeader")
    }, tags={ "ERP - units", })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "", response = Unit.class),
        @ApiResponse(code = 401, message = "Unauthorized - API key is missing or invalid", response = Error.class),
        @ApiResponse(code = 500, message = "Server error", response = Error.class) })

    @RequestMapping(value = "/units/{unitId}",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<Unit> getUnit(@ApiParam(value = "", required = true) @PathVariable("unitId") Integer unitId);


    @ApiOperation(value = "Returns list of Units", notes = "", response = Unit.class, responseContainer = "List", authorizations = {
        @Authorization(value = "APIKeyHeader")
    }, tags={ "ERP - units", })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "", response = Unit.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized - API key is missing or invalid", response = Error.class),
        @ApiResponse(code = 500, message = "Server error", response = Error.class) })

    @RequestMapping(value = "/units",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<Unit>> getUnits();


    @ApiOperation(value = "Update existing unit", notes = "", response = Void.class, authorizations = {
        @Authorization(value = "APIKeyHeader")
    }, tags={ "ERP - units", })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Updated", response = Void.class),
        @ApiResponse(code = 401, message = "Unauthorized - API key is missing or invalid", response = Error.class),
        @ApiResponse(code = 500, message = "Server error", response = Error.class) })

    @RequestMapping(value = "/units/{unitId}",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateUnit(@ApiParam(value = "", required = true) @PathVariable("unitId") Integer unitId, @ApiParam(value = "Unit to update") @Valid @RequestBody Unit unit);

}
