/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api.crm;

import io.swagger.model.Error;
import io.swagger.model.crm.MeetingNote;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-15T00:41:28.115Z")

@Api(value = "meetingNotes", description = "the meeting notes API")
public interface MeetingNotesApi {
    @ApiOperation(value = "Create new MeetingNote for given meeting", notes = "", response = Integer.class, authorizations = {
            @Authorization(value = "Authorization")
    }, tags={ "CRM - meeting notes", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "", response = Integer.class),
            @ApiResponse(code = 401, message = "Unauthorized - API key is missing or invalid", response = Error.class),
            @ApiResponse(code = 500, message = "Server error", response = Error.class) })

    @RequestMapping(value = "/crm/meetings/{meetingId}/notes",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.POST)
    ResponseEntity<Integer> createMeetingNotes(@ApiParam(value = "",required=true ) @PathVariable("meetingId") Integer meetingId,
                                               @ApiParam(value = "MeetingNote to create"  )  @Valid @RequestBody MeetingNote meetingNote);

    @ApiOperation(value = "Delete MeetingNote", notes = "", response = Void.class, authorizations = {
            @Authorization(value = "Authorization")
    }, tags={ "CRM - meeting notes", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Deleted", response = Void.class),
            @ApiResponse(code = 401, message = "Unauthorized - API key is missing or invalid", response = Error.class),
            @ApiResponse(code = 500, message = "Server error", response = Error.class) })

    @RequestMapping(value = "/crm/meetings/{meetingId}/notes/{MeetingNoteId}",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteMeetingNote(@ApiParam(value = "",required=true ) @PathVariable("meetingId") Integer meetingId,
                                           @ApiParam(value = "",required=true ) @PathVariable("MeetingNoteId") Integer meetingNoteId);


    @ApiOperation(value = "Returns note belonging to given meeting", notes = "", response = MeetingNote.class, authorizations = {
            @Authorization(value = "Authorization")
    }, tags={ "CRM - meeting notes", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "", response = MeetingNote.class),
            @ApiResponse(code = 401, message = "Unauthorized - API key is missing or invalid", response = Error.class),
            @ApiResponse(code = 500, message = "Server error", response = Error.class) })

    @RequestMapping(value = "/crm/meetings/{meetingId}/notes/{MeetingNoteId}",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<MeetingNote> getMeetingNote(@ApiParam(value = "",required=true ) @PathVariable("meetingId") Integer meetingId,
                                               @ApiParam(value = "",required=true ) @PathVariable("MeetingNoteId") Integer meetingNoteId);

    @ApiOperation(value = "Returns notes belonging to given meeting", notes = "", response = MeetingNote.class, responseContainer = "List",
            authorizations = {@Authorization(value = "Authorization")
    }, tags={ "CRM - meeting notes", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "", response = MeetingNote.class, responseContainer = "List"),
            @ApiResponse(code = 401, message = "Unauthorized - API key is missing or invalid", response = Error.class),
            @ApiResponse(code = 500, message = "Server error", response = Error.class) })

    @RequestMapping(value = "/crm/meetings/{meetingId}/notes",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<List<MeetingNote>> getMeetingNotes(@ApiParam(value = "",required=true ) @PathVariable("meetingId") Integer meetingId);


    @ApiOperation(value = "Update existing MeetingNote", notes = "", response = Void.class, authorizations = {
            @Authorization(value = "Authorization")
    }, tags={ "CRM - meeting notes", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Updated", response = Void.class),
            @ApiResponse(code = 401, message = "Unauthorized - API key is missing or invalid", response = Error.class),
            @ApiResponse(code = 500, message = "Server error", response = Error.class) })

    @RequestMapping(value = "/crm/meetings/{meetingId}/notes/{MeetingNoteId}",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.PUT)
    ResponseEntity<Void> updateMeetingNote(@ApiParam(value = "",required=true ) @PathVariable("meetingId") Integer meetingId,
                                           @ApiParam(value = "",required=true ) @PathVariable("MeetingNoteId") Integer meetingNoteId,
                                           @ApiParam(value = "MeetingNote to update"  )  @Valid @RequestBody MeetingNote meetingNote);


}
