/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api.common;

import io.swagger.model.common.Token;
import io.swagger.model.User;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-15T00:41:28.115Z")

@Api(value = "login", description = "the login API")
public interface LoginApi {

    @ApiOperation(value = "Get authentication token, roles are:crm, erp, admin", notes = "auth", response = Token.class, tags={ "employees", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Login successful", response = Token.class),
        @ApiResponse(code = 401, message = "Not authenticated", response = Void.class) })
    
    @RequestMapping(value = "/login",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Token> login(@ApiParam(value = ""  )  @Valid @RequestBody User user);

}
