///**
// * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
// * https://github.com/swagger-api/swagger-codegen
// * Do not edit the class manually.
// */
//package io.swagger.api.crm;
//
//import io.swagger.model.Error;
//
//import io.swagger.annotations.*;
//import io.swagger.model.common.Employee;
//import org.springframework.http.ResponseEntity;
//import org.springframework.web.bind.annotation.PathVariable;
//import org.springframework.web.bind.annotation.RequestBody;
//import org.springframework.web.bind.annotation.RequestMapping;
//import org.springframework.web.bind.annotation.RequestMethod;
//
//import java.util.List;
//import javax.validation.Valid;
//@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-15T00:41:28.115Z")
//
//@Api(value = "meetingEmployees", description = "the meeting employees API")
//public interface MeetingEmployeesApi {
//
//    @ApiOperation(value = "Create new Employee for given meeting", notes = "", response = Integer.class, authorizations = {
//            @Authorization(value = "APIKeyHeader")
//    }, tags={ "CRM - meeting employees", })
//    @ApiResponses(value = {
//            @ApiResponse(code = 200, message = "", response = Integer.class),
//            @ApiResponse(code = 401, message = "Unauthorized - API key is missing or invalid", response = Error.class),
//            @ApiResponse(code = 500, message = "Server error", response = Error.class) })
//
//    @RequestMapping(value = "/crm/meetings/{meetingId}/employees",
//            produces = { "application/json" },
//            consumes = { "application/json" },
//            method = RequestMethod.POST)
//    ResponseEntity<Integer> createMeetingEmployee(@ApiParam(value = "",required=true ) @PathVariable("meetingId") Integer meetingId,
//                                                   @ApiParam(value = "Employee to create"  )  @Valid @RequestBody Employee employee);
//
//
//    @ApiOperation(value = "Delete Employee", notes = "", response = Void.class, authorizations = {
//            @Authorization(value = "APIKeyHeader")
//    }, tags={ "CRM - meeting employees", })
//    @ApiResponses(value = {
//            @ApiResponse(code = 200, message = "Deleted", response = Void.class),
//            @ApiResponse(code = 401, message = "Unauthorized - API key is missing or invalid", response = Error.class),
//            @ApiResponse(code = 500, message = "Server error", response = Error.class) })
//
//    @RequestMapping(value = "/crm/meetings/{meetingId}/employees/{EmployeeId}",
//            produces = { "application/json" },
//            consumes = { "application/json" },
//            method = RequestMethod.DELETE)
//    ResponseEntity<Void> deleteMeetingEmployee(@ApiParam(value = "",required=true ) @PathVariable("meetingId") Integer meetingId,
//                                               @ApiParam(value = "",required=true ) @PathVariable("EmployeeId") Integer EmployeeId);
//
//
//    @ApiOperation(value = "Returns employee belonging to given meeting", notes = "", response = Employee.class, authorizations = {
//            @Authorization(value = "APIKeyHeader")
//    }, tags={ "CRM - meeting employees", })
//    @ApiResponses(value = {
//            @ApiResponse(code = 200, message = "", response = Employee.class),
//            @ApiResponse(code = 401, message = "Unauthorized - API key is missing or invalid", response = Error.class),
//            @ApiResponse(code = 500, message = "Server error", response = Error.class) })
//
//    @RequestMapping(value = "/crm/meetings/{meetingId}/employees/{EmployeeId}",
//            produces = { "application/json" },
//            consumes = { "application/json" },
//            method = RequestMethod.GET)
//    ResponseEntity<Employee> getMeetingEmployee(@ApiParam(value = "",required=true ) @PathVariable("meetingId") Integer meetingId,
//                                                       @ApiParam(value = "",required=true ) @PathVariable("EmployeeId") Integer EmployeeId);
//
//
//    @ApiOperation(value = "Returns employees belonging to given meeting", notes = "", response = Employee.class, responseContainer = "List",
//            authorizations = {@Authorization(value = "APIKeyHeader")
//    }, tags={ "CRM - meeting employees", })
//    @ApiResponses(value = {
//            @ApiResponse(code = 200, message = "", response = Employee.class, responseContainer = "List"),
//            @ApiResponse(code = 401, message = "Unauthorized - API key is missing or invalid", response = Error.class),
//            @ApiResponse(code = 500, message = "Server error", response = Error.class) })
//
//    @RequestMapping(value = "/crm/meetings/{meetingId}/employees",
//            produces = { "application/json" },
//            consumes = { "application/json" },
//            method = RequestMethod.GET)
//    ResponseEntity<List<Employee>> getMeetingEmployees(@ApiParam(value = "",required=true ) @PathVariable("meetingId") Integer meetingId);
//
//
//    @ApiOperation(value = "Update existing Employee", notes = "", response = Void.class, authorizations = {
//            @Authorization(value = "APIKeyHeader")
//    }, tags={ "CRM - meeting employees", })
//    @ApiResponses(value = {
//            @ApiResponse(code = 200, message = "Updated", response = Void.class),
//            @ApiResponse(code = 401, message = "Unauthorized - API key is missing or invalid", response = Error.class),
//            @ApiResponse(code = 500, message = "Server error", response = Error.class) })
//
//    @RequestMapping(value = "/crm/meetings/{meetingId}/employees/{EmployeeId}",
//            produces = { "application/json" },
//            consumes = { "application/json" },
//            method = RequestMethod.PUT)
//    ResponseEntity<Void> updateMeetingEmployee(@ApiParam(value = "",required=true ) @PathVariable("meetingId") Integer meetingId,
//                                               @ApiParam(value = "",required=true ) @PathVariable("EmployeeId") Integer EmployeeId,
//                                               @ApiParam(value = "Employee to update"  )  @Valid @RequestBody Employee meetingEmployee);
//
//}
