/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api.crm;

import io.swagger.model.Error;
import io.swagger.model.crm.TaskStatus;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-15T00:41:28.115Z")

@Api(value = "taskStatuses", description = "the taskStatuses API")
public interface TaskStatusesApi {

    @ApiOperation(value = "Create new taskStatuse", notes = "", response = Integer.class, authorizations = {
        @Authorization(value = "Authorization")
    }, tags={ "CRM - taskStatuses", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Integer.class),
        @ApiResponse(code = 401, message = "Unauthorized - API key is missing or invalid", response = Error.class),
        @ApiResponse(code = 500, message = "Server error", response = Error.class) })
    
    @RequestMapping(value = "/crm/taskStatuses",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Integer> createTaskStatuse(@ApiParam(value = "TaskStatuse to create"  )  @Valid @RequestBody TaskStatus taskStatuse);


    @ApiOperation(value = "Delete taskStatuse", notes = "", response = Void.class, authorizations = {
        @Authorization(value = "Authorization")
    }, tags={ "CRM - taskStatuses", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Deleted", response = Void.class),
        @ApiResponse(code = 401, message = "Unauthorized - API key is missing or invalid", response = Error.class),
        @ApiResponse(code = 500, message = "Server error", response = Error.class) })
    
    @RequestMapping(value = "/crm/taskStatuses/{taskStatuseId}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteTaskStatuse(@ApiParam(value = "",required=true ) @PathVariable("taskStatuseId") Integer taskStatuseId);


    @ApiOperation(value = "Returns TaskStatuse", notes = "", response = TaskStatus.class, authorizations = {
        @Authorization(value = "Authorization")
    }, tags={ "CRM - taskStatuses", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = TaskStatus.class),
        @ApiResponse(code = 401, message = "Unauthorized - API key is missing or invalid", response = Error.class),
        @ApiResponse(code = 500, message = "Server error", response = Error.class) })
    
    @RequestMapping(value = "/crm/taskStatuses/{taskStatuseId}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<TaskStatus> getTaskStatuse(@ApiParam(value = "",required=true ) @PathVariable("taskStatuseId") Integer taskStatuseId);


    @ApiOperation(value = "Returns list of TaskStatuses", notes = "", response = TaskStatus.class, responseContainer = "List", authorizations = {
        @Authorization(value = "Authorization")
    }, tags={ "CRM - taskStatuses", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = TaskStatus.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized - API key is missing or invalid", response = Error.class),
        @ApiResponse(code = 500, message = "Server error", response = Error.class) })
    
    @RequestMapping(value = "/crm/taskStatuses",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<TaskStatus>> getTaskStatuses();


    @ApiOperation(value = "Update existing taskStatuse", notes = "", response = Void.class, authorizations = {
        @Authorization(value = "Authorization")
    }, tags={ "CRM - taskStatuses", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Updated", response = Void.class),
        @ApiResponse(code = 401, message = "Unauthorized - API key is missing or invalid", response = Error.class),
        @ApiResponse(code = 500, message = "Server error", response = Error.class) })
    
    @RequestMapping(value = "/crm/taskStatuses/{taskStatuseId}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateTaskStatuse(@ApiParam(value = "",required=true ) @PathVariable("taskStatuseId") Integer taskStatuseId,@ApiParam(value = "TaskStatuse to create"  )  @Valid @RequestBody TaskStatus taskStatuse);

}
